# Generated by Django 5.2.3 on 2025-07-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmodelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posting_date', models.DateField()),
                ('location', models.CharField(max_length=30)),
                ('offered_salary', models.FloatField()),
                ('qualification', models.CharField(max_length=20)),
            ],
        ),
    ]
