# Generated by Django 5.2.3 on 2025-07-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmodelapp', '0002_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('cno', models.IntegerField()),
                ('mail_id', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('age', models.IntegerField()),
            ],
        ),
    ]
