# Generated by Django 5.2.3 on 2025-07-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmodelapp', '0003_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eno', models.IntegerField()),
                ('ename', models.CharField(max_length=30)),
                ('esal', models.FloatField()),
                ('eaddr', models.CharField(max_length=30)),
            ],
        ),
    ]
