# Generated by Django 5.2.3 on 2025-07-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmodelapp', '0004_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compid', models.IntegerField()),
                ('compname', models.CharField(max_length=30)),
                ('noofemps', models.IntegerField()),
                ('compaddr', models.CharField(max_length=30)),
                ('compsharevalue', models.FloatField()),
            ],
        ),
    ]
